export const ADMIN_CLIENTS = [
  {
    id: '1',
    name: 'Marcus Hill',
    email: 'm.hill@hillconst.com',
    initials: 'MH',
    avColor: '#D4A017',
    advisor: 'David Chen',
    loc: 'Downtown Houston',
    mrr: '$349',
    status: 'Active',
    phone: '(555) 293-1892',
  },
  {
    id: '2',
    name: 'Elena Rodriguez',
    email: 'elena@rgzmedia.com',
    initials: 'ER',
    avColor: '#2F7D79',
    advisor: 'Yvonne Hollis-Cobb',
    loc: 'Katy',
    mrr: '$599',
    status: 'Active',
    phone: '(555) 221-9044',
  },
  {
    id: '3',
    name: 'Priya Sharma',
    email: 'psharma@techstart.io',
    initials: 'PS',
    avColor: '#5B4A8B',
    advisor: 'David Chen',
    loc: 'Austin',
    mrr: '$299',
    status: 'Past Due',
    phone: '(555) 904-1188',
  },
  {
    id: '4',
    name: 'Robert Williams',
    email: 'rwilliams88@gmail.com',
    initials: 'RW',
    avColor: '#1B3A5C',
    advisor: 'Sarah Jenkins',
    loc: 'The Woodlands',
    mrr: '$199',
    status: 'Active',
    phone: '(555) 773-0021',
  },
  {
    id: '5',
    name: 'Alicia Torres',
    email: 'alicia.t@torrestax.com',
    initials: 'AT',
    avColor: '#1A7A4A',
    advisor: 'David Chen',
    loc: 'Katy',
    mrr: '$799',
    status: 'Onboarding',
    phone: '(555) 447-3908',
  },
]
